# Generated by Django 5.1 on 2024-12-16 12:19

from django.db import migrations

def create_subscription_default_price_id(apps, schema_editor):
    SubscriptionConfig = apps.get_model("subscriptions", "SubscriptionConfig")
    SubscriptionConfig.objects.create(key="subscription_default_price", value='-')


def reverse_func(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_auto_20241204_1353"),
    ]

    operations = [
        migrations.RunPython(create_subscription_default_price_id, reverse_func),
    ]
