# Generated by Django 5.1.4 on 2025-01-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="last_email_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
